require_relative '../config/environment.rb'

recipe1 = Recipe.new('Chicken Pot Pie')
recipe2 = Recipe.new('Pizza')
recipe3 = Recipe.new('Beef Stew')
recipe4 = Recipe.new('Mozarella Sticks')
ingredient01 = Ingredient.new('chicken')
ingredient02 = Ingredient.new('carrots')
ingredient03 = Ingredient.new('crust')
ingredient04 = Ingredient.new('mixed veg')
ingredient05 = Ingredient.new('peppers')
ingredient06 = Ingredient.new('potato')
ingredient07 = Ingredient.new('tomato')
ingredient08 = Ingredient.new('fish')
ingredient09 = Ingredient.new('peanut')
ingredient10 = Ingredient.new('milk')
ingredient11 = Ingredient.new('nuts')
ingredient12 = Ingredient.new('lemon')
ingredient13 = Ingredient.new('pepper')
ingredient14 = Ingredient.new('beef')
ingredient15 = Ingredient.new('butter')
ingredient16 = Ingredient.new('cheese')
r_ingredient01 = RecipeIngredient.new(recipe1, ingredient01)
r_ingredient02 = RecipeIngredient.new(recipe1, ingredient02)
r_ingredient03 = RecipeIngredient.new(recipe2, ingredient07)
r_ingredient03 = RecipeIngredient.new(recipe2, ingredient16)
r_ingredient04 = RecipeIngredient.new(recipe4, ingredient16)
user1 = User.new('Bobby Broneo')
user2 = User.new('Yennifer Young')
user3 = User.new('Jason Jones')
allergen1 = Allergen.new(user1, ingredient02)
allergen2 = Allergen.new(user3, ingredient10)
allergen3 = Allergen.new(user2, ingredient10)
recipe_c1 = RecipeCard.new(user1,recipe1, 5)
recipe_c2 = RecipeCard.new(user2,recipe1, 8)
recipe_c3 = RecipeCard.new(user3, recipe2, 9)
recipe_c4 = RecipeCard.new(user1, recipe2, 4)
recipe_c6 = RecipeCard.new(user1,recipe4, 6)
recipe_c5 = RecipeCard.new(user1,recipe3, 8)


binding.pry
