require_relative '../config/environment.rb'


recipe = Recipe.new(description: "mjnhubgyftrdrfvgbhnjmnhbgvfdse")
recipe2 = Recipe.new(description: "kmjnhubgyftrdesrdtrfvghjknhbgvfcdxsdf")
recipe3 = Recipe.new(description: "tigvyfrdeswedrfytvgbhgvfcdrxesdcfgvbh")
recipe4 = Recipe.new(description: "hbgyftdrseawsedf")
recipe5 = Recipe.new(description: "yguhkjn")
recipe6 = Recipe.new(description: "uhygtfrtugyhuknjlkm")
recipe7 = Recipe.new(description: "nhgihjkl,kmjnhbgyvft")
recipe8 = Recipe.new(description: "mkljnbhgvftcdrxs")

joy =User.new(name: "joy", age: 98)
joy2 =User.new(name: "joy2", age: 5)
joy3 =User.new(name: "joy3", age:64)
joy4 =User.new(name: "joy4", age:24)
joy5 =User.new(name: "joy5", age:33)
joy6 =User.new(name: "joy6", age:534)

tomato = Ingredient.new(name:"tomato")
potato = Ingredient.new(name:"potato")
onion = Ingredient.new(name: "onion")
apple = Ingredient.new(name:"apple")
pork = Ingredient.new(name: "pork")
butter = Ingredient.new(name: "butter")
carrot = Ingredient.new(name: "carrot")
beef = Ingredient.new(name: "beef")

Allergen.new(user:joy, ingredient:tomato)
Allergen.new(user:joy2, ingredient:tomato)
Allergen.new(user:joy5, ingredient:tomato)
Allergen.new(user:joy3, ingredient:tomato)
Allergen.new(user:joy5, ingredient:potato)
Allergen.new(user:joy4, ingredient:potato)
Allergen.new(user:joy, ingredient:potato)
Allergen.new(user:joy, ingredient:potato)
# Allergen.new(user:joy, ingredient:onion)
Allergen.new(user:joy2, ingredient:onion)
Allergen.new(user:joy5, ingredient:onion)
Allergen.new(user:joy6, ingredient:apple)
# Allergen.new(user:joy, ingredient:apple)
Allergen.new(user:joy3, ingredient:pork)
Allergen.new(user:joy, ingredient:butter)
# Allergen.new(user:joy, ingredient:carrot)
Allergen.new(user:joy4, ingredient:beef)
# Allergen.new(user:joy, ingredient:beef)
Allergen.new(user:joy4, ingredient:carrot)

RecipeCard.new(date: Date.new(2002,2,3), rating:10, user: joy , recipe:recipe4)
RecipeCard.new(date: Date.new(2001,2,3), rating:10, user:joy , recipe:recipe)
RecipeCard.new(date: Date.new(2001,2,3), rating:10, user:joy2 , recipe:recipe4)
RecipeCard.new(date: Date.new(2001,2,3), rating:9, user:joy , recipe:recipe3)
RecipeCard.new(date: Date.new(2001,2,3), rating:9, user:joy5 , recipe:recipe3)
RecipeCard.new(date: Date.new(2014,2,3), rating:9, user:joy4 , recipe:recipe3)
RecipeCard.new(date: Date.new(2001,2,3), rating:9, user:joy3 , recipe:recipe4)
RecipeCard.new(date: Date.new(2021,2,5), rating:8, user:joy6 , recipe:recipe)
RecipeCard.new(date: Date.new(2001,2,3), rating:8, user:joy5 , recipe:recipe2)
RecipeCard.new(date: Date.new(2001,2,3), rating:7, user:joy , recipe:recipe8)
RecipeCard.new(date: Date.new(2001,4,3), rating:6, user:joy2 , recipe:recipe)
RecipeCard.new(date: Date.new(2001,2,3), rating:5, user:joy6 , recipe:recipe2)
RecipeCard.new(date: Date.new(2001,7,3), rating:4, user:joy3 , recipe:recipe4)
RecipeCard.new(date: Date.new(2001,2,3), rating:3, user:joy , recipe:recipe6)
RecipeCard.new(date: Date.new(2001,2,3), rating:2, user:joy5 , recipe:recipe5)
RecipeCard.new(date: Date.new(2041,2,3), rating:6, user:joy4 , recipe:recipe4)
RecipeCard.new(date: Date.new(2001,2,3), rating:7, user:joy , recipe:recipe7)
RecipeCard.new(date: Date.new(2001,2,3), rating:5, user:joy , recipe:recipe4)
RecipeCard.new(date: Date.new(2008,2,3), rating:10, user:joy6 , recipe:recipe7)

RecipeIngredient.new(ingredient:tomato, recipe:recipe3)
RecipeIngredient.new(ingredient:potato, recipe:recipe2)
RecipeIngredient.new(ingredient:potato, recipe:recipe3)
RecipeIngredient.new(ingredient:onion, recipe:recipe4)
RecipeIngredient.new(ingredient:tomato, recipe:recipe4)
RecipeIngredient.new(ingredient:apple, recipe:recipe)
RecipeIngredient.new(ingredient:onion, recipe:recipe)
RecipeIngredient.new(ingredient:pork, recipe:recipe6)
RecipeIngredient.new(ingredient:tomato, recipe:recipe6)
RecipeIngredient.new(ingredient:apple, recipe:recipe)
RecipeIngredient.new(ingredient:beef, recipe:recipe3)
RecipeIngredient.new(ingredient:beef, recipe:recipe2)
RecipeIngredient.new(ingredient:beef, recipe:recipe5)
RecipeIngredient.new(ingredient:tomato, recipe:recipe5)
RecipeIngredient.new(ingredient:beef, recipe:recipe6)
RecipeIngredient.new(ingredient:beef, recipe:recipe7)
RecipeIngredient.new(ingredient:beef, recipe:recipe)
RecipeIngredient.new(ingredient:tomato, recipe:recipe5)
RecipeIngredient.new(ingredient:pork, recipe:recipe)
RecipeIngredient.new(ingredient:butter, recipe:recipe7)
RecipeIngredient.new(ingredient:butter, recipe:recipe8)
RecipeIngredient.new(ingredient:carrot, recipe:recipe8)
RecipeIngredient.new(ingredient:carrot, recipe:recipe)
binding.pry
